### ISSUE TITLE
Publish version 1.1.4 to Puppet Forge?

### ISSUE THREAD

**Issue by westbywest** [deric/puppet-accounts#34]
Version 1.1.4 of this module was checked into the master branch in July 2015.  Puppet Forge is still reporting v1.1.3, and indeed the tarball from Forge reports v1.1.3 in its metadata.json.  Possible to bring Forge up to date with the latest stable version here in Github?  Or is v1.1.4 not yet ready for release?

https://forge.puppetlabs.com/deric/accounts

**Comment by deric** [comment]
There ain't much [changes](https://github.com/deric/puppet-accounts/compare/v1.1.3...master) since [1.1.3](https://github.com/deric/puppet-accounts/releases/tag/v1.1.3). Before releasing new version I wanted to add proper tests. Probably acceptance testing on different OS with [Beaker](https://github.com/puppetlabs/beaker), because otherwise it's really hard to introduce new features without breaking already working stuff.

**Comment by deric** [comment]
Ok, there won't be 1.1.4 release. I've released all the latest fixes as [v1.2.0](https://github.com/deric/puppet-accounts/releases/tag/v1.2.0) and it is available at Forge.
