### ISSUE TITLE
# TODO: implement purge_ssh_keys manually?

### ISSUE THREAD

**Issue by internaught** [deric/puppet-accounts#47]
Please add a way to make purge_ssh_keys work with puppet 3.4.3!

Module works great otherwise and I'd love to use it but, this is the main functionality that I'm looking for.

```puppet
      user { $username:
        ensure  => absent,
        uid     => $uid,
        gid     => $real_gid,
        require => Anchor["accounts::user::remove_${name}"],
      }

      if $manage_group == true {
        group { $primary_group:
          ensure  => absent,
          gid     => $real_gid,
          require => User[$username],
        }
      }
    }
    'present': {
      # prior to Puppet 3.6 `purge_ssh_keys` is not supported
      if versioncmp($::puppetversion, '3.6.0') < 0 {
        user { $username:
          ensure  => present,
          uid     => $uid,
          gid     => $real_gid,
          #groups  => $groups, # managed via groups class
          shell   => $shell,
          comment => $comment,
        }
        # TODO: implement purge_ssh_keys manually?
        if $purge_ssh_keys {
          notice('$purge_ssh_keys not supported prior to puppet 3.6.0')
        }
```

**Comment by deric** [comment]
I rewrote keys management. Right now `authorized_keys` are overwritten by a simple Puppet template and `ssh_authorized_key` resource is not used at all with `purge_ssh_keys`. It might cause some problems (like you can't use [options](https://docs.puppet.com/puppet/latest/reference/types/ssh_authorized_key.html#ssh_authorized_key-attribute-options)) or random ssh keys changes due to different ordering in hash etc.
